### login
POST https://jwt-auth-eight-neon.vercel.app/login
Content-Type: application/json

{
  "email": "111202315327@mhs.dinus.ac.id",
  "password": "123456"
}

### logout
POST https://jwt-auth-eight-neon.vercel.app/logout
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzMiwibmFtZSI6IkFCRFVMIiwiZW1haWwiOiIxMTEyMDIzMTUzMjdAbWhzLmRpbnVzLmFjLmlkIiwiaWF0IjoxNzgzNjA4OTQ5LCJleHAiOjE3ODM2OTUzNDl9.6XQOksz_-a21XTQFSnkQji9YldWUwt0ZWZ26K0p0VhY